### ISSUE TITLE
<a> element insert in makisu selector

### ISSUE THREAD

**Issue by amontanari** [soulwire/Makisu#11]
Hi,
i tryed to create a little navigatin menu with this lib, the animation is ok on all browser type but on firefox i found a problem: the internal link in <'li'> is not find from mouse in firefox.
My set:
<code>
  $('#menu').makisu({
    selector: 'li',
    overlap: 0.2,
    speed: 0.2
  });

<code>
 <'ul id="menu"'>
   <'li>
       <'a href="#page1">Page1</a>
       <'div class="caption"><p>capition Page1</p></div>
   <'/li>
   <'li>
       <'a href="#page2">Page2</a>
       <'div class="caption"><p>capition Page2</p></div>
   </li>
   <'li>
       <'a href="#page3">Page3</a>
       <'div class="caption"><p>capition Page3</p></div>
   <'/li>
 <'/ul>
</code>
</code>
in css #menu li>a have height and width of all parent li

Is perfect with Chrome but I don't understand why with Firefox i found this problem.
If i set z-index of <'li'> and of <'a'> can i resolve my problem?

thx for your attention.
Best Regards, 
Alberto

**Comment by Eliyahna** [comment]
I have the same problem did you ever find the solution?

**Comment by amontanari** [comment]
Hi, we can close this Issue (question), i set correctly the z-index property and the problem is solved.
Example:

#menu { 
  position: relative;
  z-index: 12;
}

#menu li {
  position: relative;
  z-index: 13;
}

 do a test, and let me know.
Best regards.

**Comment by Eliyahna** [comment]
<p> I did this, which is I think what you suggested:</p>

<p>.nigiri {</p>

<p> -webkit-transform: perspective(1200px) rotateY(40deg) !important;<br />
  -moz-transform: perspective(1200px) rotateY(40deg) !important;<br />
  -ms-transform: perspective(1200px) rotateY(40deg) !important;<br />
  -o-transform: perspective(1200px) rotateY(40deg) !important;<br />
  transform: perspective(1200px) rotateY(40deg) !important;</p>

<p> -webkit-transform-origin: 110% 25%;<br />
  -moz-transform-origin: 110% 25%;<br />
  -ms-transform-origin: 110% 25%;<br />
  -o-transform-origin: 110% 25%;<br />
  transform-origin: 110% 25%;<br />
  left: 20%;<br />
  <strong>position:relative;<br />
  z-index: 12;</strong><br />
  }</p>

<p>and</p>

<p>.nigiri dt, .nigiri dd, .nigiri a { <br />
  background: #789962;<br />
  <strong>position:relative;<br />
  z-index:13;</strong><br />
}</p>

<p>on style.css but the whole thing disappeared, it didn't fix it. I am using this index.html from the master zip file. I have not set any other z-index properties.</p>

<p>&nbsp;</p>

**Comment by amontanari** [comment]
I don't have the problem after a good revision of all z-index.
https://developer.mozilla.org/en-US/docs/CSS/Understanding_z-index

In my case:

with this html (JADE):

<code><pre>
body(data-spy="scroll", data-target="#nav") <-- this because i use bootstrap scrollspy 
    #header
        ul#menu.nav
            li#menu-page1.mainmenu
                a.nav-button(href='#page1') page1
                .menu-caption
                    p page1
            li#menu-page2.mainmenu
                a.nav-button(href='#page2') page2
                .menu-caption
                    p page2
                ul#services-submenu
                    li#menu-page3.submenu
                        a.subnav-button(href='#page3') page3
                        .submenu-caption
                            p page3
                    li#menu-page4.submenu
                        a.subnav-button(href='#page4') page4
                        .submenu-caption
                            p page4
            li#menu-page5.mainmenu
                a.nav-button(href='#page5') page5
                .menu-caption
                    p page5
</pre>
</code>

my css (in less)

<pre>
body {
  position: relative;
  z-index: 0;
}
#header {
  position: fixed;
  top: 0;
  z-index: 1000;
}
#nav {
  position: fixed;
  top: 150px;
  left: 10px;
  width: 62px;
  z-index: 1001;
}
#menu {
  position: relative;
  z-index: 1002;
}
#menu {
  >li {
    >a:hover {
      background-color: transparent;
    }
  }
}
.nav-button {
  position: relative;
  display: block;
  height: 62px;
  width: 62px;
  text-indent: 100%;
  overflow: hidden;
  z-index: 1004;
}
.subnav-button {
  position: relative;
  display: block;
  height: 47px;
  width: 62px;
  text-indent: 100%;
  overflow: hidden;
  z-index: 1004;
}
</pre>

I hope that can help you.

**Comment by Eliyahna** [comment]
Thank you. I understand about z-index. I have used it before. The problem is you are not using the same web page that I am trying to work on. I am commenting and working on Makisu ~ CSS 3D Dropdown Concept which also a .js file which contains transform commands for the animation translateZ(-0.1px. I believe these are affecting things as well and if they are removed or changed they adversely affect the animation of the foldout.

I understand what you're doing with yours I'm just not sure how to apply that to this project.

Thanks again for trying to help me.

**Comment by amontanari** [comment]
ok, help is not a problem :) 
I studied the makisu js, but for my problem my solution was found only with the correct settings of murkup and css. The css trasformation that makisu js does on murkup and on css's property not create problem on selection of a link <a> inside the list element.

Regards :)

**Comment by Eliyahna** [comment]
Ah I see :) Well for this Nigiri, the section on the HTML looks like this:

<p>&lt;section class=&quot;demo&quot;&gt;</p>

<p> &lt;dl class=&quot;list nigiri&quot;&gt;<br />
  &lt;dt&gt;&lt;a href=&quot;one.html&quot; id=&quot;default&quot; onClick=&quot;changeFrame(this.href); return false;&quot;&gt;One&lt;/a&gt;&lt;/dt&gt;<br />
  &lt;dd&gt;&lt;a href=&quot;two.html&quot; id=&quot;default&quot; onClick=&quot;changeFrame(this.href); return false;&quot;&gt;Two&lt;/a&gt;&lt;/dd&gt;<br />
  &lt;dd&gt;&lt;a href=&quot;three.html&quot;&gt;Three&lt;/a&gt;&lt;/dd&gt;<br />
  &lt;dd&gt;&lt;a href=&quot;four.html&quot;&gt;Four&lt;/a&gt;&lt;/dd&gt;<br />
  &lt;dd&gt;&lt;a href=&quot;five.html&quot;&gt;Five&lt;/a&gt;&lt;/dd&gt;<br />
  &lt;dd&gt;&lt;a href=&quot;six.html&quot;&gt;Six&lt;/a&gt;&lt;/dd&gt;<br />
  &lt;dd&gt;&lt;a href=&quot;seven.html&quot;&gt;Seven&lt;/a&gt;&lt;/dd&gt;<br />
  &lt;dd&gt;&lt;a href=&quot;eight.html&quot;&gt;Eight&lt;/a&gt;&lt;/dd&gt;<br />
  &lt;dd&gt;&lt;a href=&quot;nine.html&quot;&gt;Nine&lt;/a&gt;&lt;/dd&gt;<br />
  &lt;/dl&gt;</p>

<p> </p>

<p> </p>

<p> &lt;/section&gt;</p>

I made the " .list dd " to z-index: 999; and also the .list to z-index: 999; and I tried to make .demo:after to z-index: 999; but nothing changed. The top < dt > works to link but not the < dd > (in Firefox)

**Comment by Eliyahna** [comment]
I have found that in Makisu.js on lines 346 & 350 I changed:

 'transform': 'translateZ(-0.1px)'
to
'transform': 'translateZ(-1px)'

Now the links are showing in both Firefox and Chrome but they do not show in IE.

**Comment by amontanari** [comment]
like I said, I tried to change the css trasformation that the makisu.js applies to the markup, but my problem was due only to the properties of z-index of the elements (z-index only works on positioned elements (position:absolute, position:relative, or position:fixed)), and that the dimensions (width and height) assigned to the link <a> actually covered up all the space element of the list <li>.
sorry.

**Comment by Eliyahna** [comment]
Yes now I'm trying to figure out where to place the position statement to satisfy IE.

**Comment by Eliyahna** [comment]
SOLVED! 

<p>Okay here is the complete solution to make this work with links in all 3 browsers:</p>

<p>On style.css line 244 change:</p>

<p>.nigiri dt, .nigiri dd, .nigiri a { <br />
  background: #789962;<br />
  }</p>

<p>to</p>

<p>.nigiri dt, .nigiri dd, .nigiri a { <br />
  background: #789962;<br />
position: relative;<br />
z-index:999;<br />
}</p>

<p>&nbsp;</p>

<p>Then on Makisu.js on lines 346 &amp; 350 change:</p>

<p>'transform': 'translateZ(-0.1px)'
<br /><br />
  to
<br /><br />
  'transform': 'translateZ(-1px)'</p>

:)

**Comment by Gori** [comment]
This isn't solved, with (-1px) translateZ things turn upside down in Firefox.

**Comment by Eliyahna** [comment]
Looks fine in Firefox to me...

The Z is for the layer depth not for direction.
