### ISSUE TITLE
Mobile safari support

### ISSUE THREAD

**Issue by yogaraptor** [soulwire/Makisu#2]
Demo doesn't seem to run on mobile Safari (5.1), but can't see a reason why not as CSS transforms etc all supported in the browser. Not had time to test on other versions. Looks lovely in Chrome tho ;)

**Comment by soulwire** [comment]
Looks like a problem with the detection script, I'll look into it!

**Comment by omegajunior** [comment]
Confirming detection failure on iOS 5.1 with mobile Safari. The browser definitely does support CSS3D transformations, as I have used it primarily to build my 3d maze game.

**Comment by cassininazir** [comment]
Had similar issues on my iPad 3.

**Comment by braaam** [comment]
You can use modernizr feature detection to fix it quickly (make sure you tick the 'prefixed' option in modernizr build tool): 

``` javascript
var canRun = Modernizr.prefixed('Perspective') in el.style;
var prefix = '-' + Modernizr.prefixed('Perspective').split('Perspective')[0].toLowerCase() + '-';
```
