### ISSUE TITLE
Issues with Chrome 24

### ISSUE THREAD

**Issue by bendoerr** [soulwire/Makisu#3]
Animations and text fail to render with Chrome 24.

**Comment by soulwire** [comment]
Looks ok to me in Canary (24). What are your platform specs?

**Comment by mrcrgl** [comment]
Look ok on Chrome Version 22.0.1229.94, OS X.

**Comment by bendoerr** [comment]
Version 24.0.1297.0 dev, OS X

Screenshot of dropdown in progress
![dropdown](https://dl-web.dropbox.com/get/Public/Makisu%20-%20Chrome%2024%20OSX.png?w=420df7b6)

**Comment by bendoerr** [comment]
A little more investigation shows this isn't likely an issue with Makisu.

chrome://gpu-internals/ is reporting errors with hardware acceleration for me. If @mrcrgl agrees then this is a non issue.

**Comment by bendoerr** [comment]
Starting chrome with --ignore-gpu-blacklist and checking out the demo works great. Sorry to concern you with this.
