### ISSUE TITLE
Unfocused tab causes rapid wrap/unwrap

### ISSUE THREAD

**Issue by Twoje** [soulwire/Makisu#5]
If you click the toggle button and go to a different tab (must be same browser window), then switch back a few seconds later, the dropdown will have a 'whip' effect. Not sure if intentional, but it looks kind of janky.

**Comment by soulwire** [comment]
This is a symptom of all CSS animations and I don't know if a workaround for it. Animations don't render when the page is blurred though the clock keeps running - when focus is regained they 'catch up' which is what you're seeing. You can see the same effect in this bare-bones example: http://jsfiddle.net/soulwire/u8C4f/
